# Generated by Django 4.0.3 on 2022-03-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_author_authoruser_author_authoruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribers',
            new_name='subscribe',
        ),
    ]
